//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftSql2012Samples.Amo2Tabular.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftSql2012Samples.Amo2Tabular.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove RowNumber column from table..
        /// </summary>
        internal static string CannotRemoveRowNumberColumnInvalidOperationException {
            get {
                return ResourceManager.GetString("CannotRemoveRowNumberColumnInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update or modify RowNumber column in table..
        /// </summary>
        internal static string CannotUpdateModifyRowNumberColumnInvalidOperationException {
            get {
                return ResourceManager.GetString("CannotUpdateModifyRowNumberColumnInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cube object already exists..
        /// </summary>
        internal static string CubeAlreadyExistsInvalidOperationException {
            get {
                return ResourceManager.GetString("CubeAlreadyExistsInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type &apos;{0}&apos; is not supported in Tabular models..
        /// </summary>
        internal static string DataTypeNotSupportedException {
            get {
                return ResourceManager.GetString("DataTypeNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given date column: {0}, is not unique..
        /// </summary>
        internal static string DateColumnIsNotUniqueInvalidOperationException {
            get {
                return ResourceManager.GetString("DateColumnIsNotUniqueInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Compatibility Level in server or database.
        /// </summary>
        internal static string InvalidCompatibilityLevelOperationException {
            get {
                return ResourceManager.GetString("InvalidCompatibilityLevelOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of &apos;{0}&apos; cubes in the database. Tabular models require only 1 cube..
        /// </summary>
        internal static string InvalidNumberOfCubesInvalidOperationException {
            get {
                return ResourceManager.GetString("InvalidNumberOfCubesInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name..
        /// </summary>
        internal static string InvalidUserNameArgumentException {
            get {
                return ResourceManager.GetString("InvalidUserNameArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI already exist..
        /// </summary>
        internal static string KpiAlreadyExistInvalidOperationException {
            get {
                return ResourceManager.GetString("KpiAlreadyExistInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI does not exist..
        /// </summary>
        internal static string KpiDoesNotExistInvalidOperationException {
            get {
                return ResourceManager.GetString("KpiDoesNotExistInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mdx script header already exists..
        /// </summary>
        internal static string MdxScriptHeaderAlreadyExistsInvalidOperationException {
            get {
                return ResourceManager.GetString("MdxScriptHeaderAlreadyExistsInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure already exist..
        /// </summary>
        internal static string MeasureAlreadyExistInvalidOperationException {
            get {
                return ResourceManager.GetString("MeasureAlreadyExistInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A measure with the same name already exists..
        /// </summary>
        internal static string MeasureAlreadyExistsInvalidOperationException {
            get {
                return ResourceManager.GetString("MeasureAlreadyExistsInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A measure with that name doesn&apos;t exists..
        /// </summary>
        internal static string MeasureDoesntExistsInvalidOperationException {
            get {
                return ResourceManager.GetString("MeasureDoesntExistsInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} function not implemented..
        /// </summary>
        internal static string NotImplementedExceptionFunction {
            get {
                return ResourceManager.GetString("NotImplementedExceptionFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name cannot be null..
        /// </summary>
        internal static string NullArgumentExceptionDatabaseName {
            get {
                return ResourceManager.GetString("NullArgumentExceptionDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to server instance cannot be null..
        /// </summary>
        internal static string NullArgumentExceptionServer {
            get {
                return ResourceManager.GetString("NullArgumentExceptionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLEDB provider not supported..
        /// </summary>
        internal static string OleDbProviderNotSupportedException {
            get {
                return ResourceManager.GetString("OleDbProviderNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A process request was issued for an outdated model; update server instance before processing..
        /// </summary>
        internal static string ProcessRequestedForOutdatedModelInvalidOperationException {
            get {
                return ResourceManager.GetString("ProcessRequestedForOutdatedModelInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship already exist..
        /// </summary>
        internal static string RelationshipAlreadyExistInvalidOperationException {
            get {
                return ResourceManager.GetString("RelationshipAlreadyExistInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship doesn&apos;t exist..
        /// </summary>
        internal static string RelationshipDoesNotExistInvalidOperationException {
            get {
                return ResourceManager.GetString("RelationshipDoesNotExistInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating this relationship violates the only one path between two tables rule for relationships..
        /// </summary>
        internal static string RelationshipViolatesAlternatePathRuleInvalidOperationException {
            get {
                return ResourceManager.GetString("RelationshipViolatesAlternatePathRuleInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database compatibility level different than expected..
        /// </summary>
        internal static string WrongDatabaseCompatibilityLevelApplicationException {
            get {
                return ResourceManager.GetString("WrongDatabaseCompatibilityLevelApplicationException", resourceCulture);
            }
        }
    }
}
