//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftSql2012Samples.AdventureWorksTabularAMO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicrosoftSql2012Samples.AdventureWorksTabularAMO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding table &apos;{1}&apos; to perspective &apos;{0}&apos;..
        /// </summary>
        internal static string AddingTableToPerspectiveConsoleMessage {
            get {
                return ResourceManager.GetString("AddingTableToPerspectiveConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdventureWorks Tabular AMO 2012.
        /// </summary>
        internal static string AdventureWorksTabularAmoDbName {
            get {
                return ResourceManager.GetString("AdventureWorksTabularAmoDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Calculated Columns:.
        /// </summary>
        internal static string CalculatedColumnsConsoleMessage {
            get {
                return ResourceManager.GetString("CalculatedColumnsConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Columns:.
        /// </summary>
        internal static string ColumnsConsoleMessage {
            get {
                return ResourceManager.GetString("ColumnsConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating objects on &apos;{0}&apos; with dependencies.
        /// </summary>
        internal static string CreatingObjectsWithDependenciesConsoleMessage {
            get {
                return ResourceManager.GetString("CreatingObjectsWithDependenciesConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating &apos;{0}&apos; role.
        /// </summary>
        internal static string CreatingRolesConsoleMessage {
            get {
                return ResourceManager.GetString("CreatingRolesConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmoAdventureWorksDW2012.
        /// </summary>
        internal static string cubeName {
            get {
                return ResourceManager.GetString("cubeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdventureWorksDW2012.
        /// </summary>
        internal static string dataSourceDbName {
            get {
                return ResourceManager.GetString("dataSourceDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=SQLOLEDB;Data Source=(local);Integrated Security=SSPI;Initial Catalog=AdventureWorksDW2012.
        /// </summary>
        internal static string dataSourceOleDb {
            get {
                return ResourceManager.GetString("dataSourceOleDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defining partitions for &apos;{0}&apos;.
        /// </summary>
        internal static string DefiningPartitionsConsoleMessage {
            get {
                return ResourceManager.GetString("DefiningPartitionsConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Hierarchies:.
        /// </summary>
        internal static string HierarchiesConsoleMessage {
            get {
                return ResourceManager.GetString("HierarchiesConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     KPIs:.
        /// </summary>
        internal static string KpisConsoleMessage {
            get {
                return ResourceManager.GetString("KpisConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ------------------------------------------------------------------------------------------------.
        /// </summary>
        internal static string LineSeparatorConsoleMessage {
            get {
                return ResourceManager.GetString("LineSeparatorConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string Localhost {
            get {
                return ResourceManager.GetString("Localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Measures:.
        /// </summary>
        internal static string MeasuresConsoleMessage {
            get {
                return ResourceManager.GetString("MeasuresConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging partitions: {0} .
        /// </summary>
        internal static string MergingPartitionsConsoleMessage {
            get {
                return ResourceManager.GetString("MergingPartitionsConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting...   {0}.
        /// </summary>
        internal static string StartingFunctionCallConsoleMessage {
            get {
                return ResourceManager.GetString("StartingFunctionCallConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting...   PerspectiveAdd &apos;{0}&apos;..
        /// </summary>
        internal static string StartingPerspectiveAddConsoleMessage {
            get {
                return ResourceManager.GetString("StartingPerspectiveAddConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting...   Process database default.
        /// </summary>
        internal static string StartingProcessDatabaseConsoleMessage {
            get {
                return ResourceManager.GetString("StartingProcessDatabaseConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting...   RelationshipAdd &apos;{0}&apos;.[{1}] &lt;--- &apos;{2}&apos;.[{3}].
        /// </summary>
        internal static string StartingRelationshipAddConsoleMessage {
            get {
                return ResourceManager.GetString("StartingRelationshipAddConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0}.
        /// </summary>
        internal static string TableElementsReportConsoleMessage {
            get {
                return ResourceManager.GetString("TableElementsReportConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables:.
        /// </summary>
        internal static string TablesConsoleMessage {
            get {
                return ResourceManager.GetString("TablesConsoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}.
        /// </summary>
        internal static string TablesReportConsoleMessage {
            get {
                return ResourceManager.GetString("TablesReportConsoleMessage", resourceCulture);
            }
        }
    }
}
